import Link from 'next/link'
import { ArrowRight, Check, MapPin, Sparkles, UsersRound } from 'lucide-react'

const logoUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/logo.png-uwI5A8ZNvAMkMsETNQ1r3EmSiqyoOq.webp'

export default function IntroductionPage() {
  return <main className="min-h-screen overflow-hidden bg-[#fbfdff] text-[#17243f]">
    <header className="relative z-10 mx-auto flex h-[82px] max-w-[1240px] items-center justify-between px-6 lg:px-10"><Link href="/" className="flex items-center gap-2.5"><img src={logoUrl} alt="이루 로고" className="h-9 w-9 object-contain" /><span className="text-[22px] font-bold tracking-[-0.08em]">이루</span></Link><Link href="/" className="flex items-center gap-1.5 text-sm font-semibold text-[#6797e8]">모임 찾으러 가기 <ArrowRight size={16} /></Link></header>
    <section className="relative mx-auto grid max-w-[1240px] items-center gap-14 px-6 pb-20 pt-14 lg:grid-cols-[1fr_0.92fr] lg:px-10 lg:pb-28 lg:pt-24">
      <div className="relative z-10"><p className="mb-5 flex items-center gap-2 text-sm font-bold tracking-[0.2em] text-[#6b9cf1]"><Sparkles size={16} /> ABOUT IRU</p><h1 className="text-[48px] font-bold leading-[1.15] tracking-[-0.07em] sm:text-[70px]">우리의 하루가<br /><span className="gradient-text">이루어지는 곳</span></h1><p className="mt-7 max-w-[440px] text-[17px] leading-8 text-[#8390a9]">혼자라서 망설였던 일들을<br />이제는 좋은 사람들과 함께 시작해요.</p><Link href="/" className="mt-9 inline-flex items-center gap-2 rounded-full bg-[#579cf0] px-6 py-3.5 text-sm font-bold text-white shadow-[0_12px_22px_rgba(87,156,240,0.23)] transition hover:-translate-y-0.5 hover:bg-[#478de5]">내 주변 모임 둘러보기 <ArrowRight size={17} /></Link></div>
      <div className="relative flex min-h-[430px] items-center justify-center"><div className="absolute h-[360px] w-[360px] rounded-full bg-gradient-to-br from-[#e2f7ff] via-[#d6e8ff] to-[#efe7ff] blur-[2px] sm:h-[470px] sm:w-[470px]" /><div className="relative w-[270px] rounded-[34px] border border-white/80 bg-white/80 p-4 shadow-[0_22px_70px_rgba(95,138,207,0.2)] backdrop-blur-xl sm:w-[330px]"><div className="rounded-[24px] bg-gradient-to-br from-[#70cff1] via-[#76acf5] to-[#9583f1] p-6 text-white"><p className="text-xs font-semibold text-white/75">TODAY&apos;S MEETUP</p><h3 className="mt-14 text-[25px] font-bold tracking-[-0.05em]">함께라서 더<br />즐거운 하루</h3><div className="mt-8 flex items-center justify-between text-xs"><span>서울숲 · 오후 2시</span><span className="rounded-full bg-white/20 px-2.5 py-1">8명 참여</span></div></div><div className="flex items-center gap-3 px-2 pt-4"><div className="flex -space-x-2"><span className="avatar bg-[#ffc5a8]" /><span className="avatar bg-[#c8b9ff]" /><span className="avatar bg-[#addfff]" /></div><p className="text-xs font-medium text-[#8a96ab]">새로운 인연이 기다리고 있어요</p></div></div></div>
      <div className="absolute -left-24 top-16 h-52 w-52 rounded-full bg-[#e4f8ff] blur-3xl" /><div className="absolute -right-24 bottom-10 h-64 w-64 rounded-full bg-[#eee8ff] blur-3xl" />
    </section>
    <section id="guide" className="border-t border-[#eef3fa] bg-white"><div className="mx-auto max-w-[1240px] px-6 py-20 lg:px-10"><div className="mb-12 text-center"><p className="text-sm font-bold tracking-[0.18em] text-[#6b9cf1]">WHY IRU</p><h2 className="mt-3 text-[32px] font-bold tracking-[-0.05em]">시작은 가볍게, 연결은 자연스럽게</h2></div><div className="grid gap-4 md:grid-cols-3"><Feature icon={<MapPin />} title="내 주변에서 발견해요" text="지도를 보며 지금 가까운 곳에서 열리는 모임을 한눈에 찾아보세요." /><Feature icon={<UsersRound />} title="취향으로 연결돼요" text="관심사와 활동을 기준으로 나와 잘 맞는 사람들을 만나요." /><Feature icon={<Check />} title="작은 약속을 이루어요" text="오늘 하고 싶었던 일을 함께할 사람과 바로 시작해보세요." /></div></div></section>
  </main>
}
function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="rounded-[24px] border border-[#edf2f8] bg-[#fbfdff] p-7"><div className="mb-6 flex h-11 w-11 items-center justify-center rounded-2xl bg-[#eaf4ff] text-[#609bf0]">{icon}</div><h3 className="mb-2 text-[18px] font-bold">{title}</h3><p className="text-sm leading-6 text-[#8a96ab]">{text}</p></article> }
